// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxTyteaT3LfDLozzZacECdVwOlOP0drtA',
    appId: '1:818288441092:web:aff50f61d50cd988584251',
    messagingSenderId: '818288441092',
    projectId: 'aventure-485f1',
    authDomain: 'aventure-485f1.firebaseapp.com',
    storageBucket: 'aventure-485f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP2ZnQrs_DEkPHG6OZ-Udu6KHMYrtHvK0',
    appId: '1:818288441092:android:e6473928ef3b2098584251',
    messagingSenderId: '818288441092',
    projectId: 'aventure-485f1',
    storageBucket: 'aventure-485f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6hE01f12toppJGRJ6cWujiXko4s8zRPE',
    appId: '1:818288441092:ios:a1bdca2b77cffda1584251',
    messagingSenderId: '818288441092',
    projectId: 'aventure-485f1',
    storageBucket: 'aventure-485f1.appspot.com',
    iosBundleId: 'com.example.aventure',
  );
}
